services:
  - type: web
    name: uptrack-rest-api
    env:
      - key: DATABASE_URL
        value: mysql://${root}:${password}@${localhost}/${users}
      - key: NODE_ENV
        value: production
    depends_on:
      - service: uptrack_server
